branch-defaults:
  aws:
    environment: awstodo-dev
  main:
    environment: awstodoapp
environment-defaults:
  awstodo-dev:
    branch: null
    repository: null
global:
  application_name: awstodo
  branch: null
  default_ec2_keyname: aws-ebtodo
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
